remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: SuperHear Pro
description: Privacy Policy for SuperHear Pro App
show_downloads: false

github:
  is_project_page: false
